# Generated by Django 5.2.5 on 2025-08-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptabiliteAppartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('revenu', 'Revenu'), ('charge', 'Charge')], max_length=10)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('date_mouvement', models.DateField(verbose_name='Date')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartements.appartement')),
            ],
            options={
                'verbose_name': 'Mouvement Comptable',
                'verbose_name_plural': 'Mouvements Comptables',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
