# Generated by Django 5.2.3 on 2025-09-05 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0001_initial'),
        ('comptabilite', '0002_initial'),
        ('reservations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comptabiliteappartement',
            index=models.Index(fields=['appartement', 'date_mouvement'], name='comptabilit_apparte_d5289c_idx'),
        ),
        migrations.AddIndex(
            model_name='comptabiliteappartement',
            index=models.Index(fields=['type_mouvement', 'date_mouvement'], name='comptabilit_type_mo_f6dab1_idx'),
        ),
    ]
