# Generated by Django 5.2.3 on 2025-08-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartements', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('nombre_nuits', models.PositiveIntegerField(default=1, verbose_name='Nombre de nuits')),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix total (FCFA)')),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='confirmee', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartements.appartement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_arrivee'],
            },
        ),
    ]
