<<<<<<< HEAD:avis/migrations/0003_initial.py
# Generated by Django 5.2.4 on 2025-07-10 20:31
=======
# Generated by Django 5.2.3 on 2025-08-07 12:42
>>>>>>> 9ea9fdf5ac234f463a66c620bbbe53de6e1ed62b:apps/reservations/migrations/0002_initial.py

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gestionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
