# Generated by Django 5.2.3 on 2025-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la réduction appliquée sur le prix total', max_digits=10, verbose_name='Réduction (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='confirmee', max_length=20),
        ),
    ]
