# Generated by Django 5.2.3 on 2025-06-28 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_remove_reservation_client_remove_reservation_maison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('categorie', models.CharField(choices=[('chambre', 'Chambre'), ('salon', 'Salon'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('exterieur', 'Extérieur'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie')),
                ('icone', models.CharField(default='cube', help_text="Icône pour l'affichage", max_length=50)),
            ],
            options={
                'verbose_name': 'Type de meuble',
                'verbose_name_plural': 'Types de meubles',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du meuble')),
                ('numero_serie', models.CharField(help_text="Numéro d'identification unique du meuble", max_length=50, unique=True, verbose_name='Numéro de série')),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], default='bon', max_length=20, verbose_name='État du meuble')),
                ('date_entree', models.DateField(default=django.utils.timezone.now, help_text="Date d'acquisition ou d'installation", verbose_name="Date d'entrée")),
                ('date_derniere_verification', models.DateField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('marque', models.CharField(blank=True, max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('couleur', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('materiaux', models.CharField(blank=True, max_length=100, verbose_name='Matériaux')),
                ('dimensions', models.CharField(blank=True, help_text='Ex: L120 x P60 x H75 cm', max_length=100, verbose_name='Dimensions')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat (FCFA)")),
                ('valeur_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur actuelle estimée (FCFA)')),
                ('piece', models.CharField(choices=[('salon', 'Salon'), ('chambre_1', 'Chambre 1'), ('chambre_2', 'Chambre 2'), ('chambre_3', 'Chambre 3'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('terrasse', 'Terrasse'), ('balcon', 'Balcon'), ('garage', 'Garage'), ('autre', 'Autre')], default='salon', max_length=30, verbose_name='Pièce')),
                ('notes', models.TextField(blank=True, help_text="Remarques sur l'état, l'utilisation, les réparations, etc.", verbose_name='Notes et observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meubles', to='home.maison', verbose_name='Maison')),
                ('type_meuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meubles.typemeuble', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Meuble',
                'verbose_name_plural': 'Meubles',
                'ordering': ['maison', 'piece', 'type_meuble', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEtatMeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_etat', models.CharField(choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], max_length=20)),
                ('nouvel_etat', models.CharField(choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], max_length=20)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True, help_text="Explication du changement d'état", verbose_name='Motif du changement')),
                ('cout', models.DecimalField(blank=True, decimal_places=2, help_text='Coût de la réparation ou du remplacement', max_digits=8, null=True, verbose_name='Coût (FCFA)')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_etats', to='meubles.meuble')),
            ],
            options={
                'verbose_name': "Historique d'état",
                'verbose_name_plural': "Historiques d'états",
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meubles/photos/', verbose_name='Image')),
                ('titre', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('type_photo', models.CharField(choices=[('etat_general', 'État général'), ('detail', 'Détail'), ('defaut', 'Défaut/problème'), ('reparation', 'Après réparation')], default='etat_general', max_length=20, verbose_name='Type de photo')),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
                ('meuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meubles.meuble')),
            ],
            options={
                'verbose_name': 'Photo de meuble',
                'verbose_name_plural': 'Photos de meubles',
                'ordering': ['-date_prise'],
            },
        ),
        migrations.CreateModel(
            name='InventaireMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateTimeField(auto_now_add=True)),
                ('type_inventaire', models.CharField(choices=[('entree', "État des lieux d'entrée"), ('sortie', 'État des lieux de sortie'), ('periodique', 'Inventaire périodique'), ('maintenance', 'Inventaire maintenance')], default='periodique', max_length=20, verbose_name="Type d'inventaire")),
                ('nombre_meubles_total', models.PositiveIntegerField(default=0)),
                ('nombre_meubles_bon_etat', models.PositiveIntegerField(default=0)),
                ('nombre_meubles_defectueux', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True, verbose_name='Observations générales')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='home.maison')),
                ('photos', models.ManyToManyField(blank=True, to='meubles.photomeuble', verbose_name="Photos de l'inventaire")),
            ],
            options={
                'verbose_name': 'Inventaire de maison',
                'verbose_name_plural': 'Inventaires de maisons',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['maison', 'etat'], name='meubles_meu_maison__b15773_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['numero_serie'], name='meubles_meu_numero__b59e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['type_meuble'], name='meubles_meu_type_me_9163ec_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['date_derniere_verification'], name='meubles_meu_date_de_fe7755_idx'),
        ),
    ]
