# Generated by Django 5.2.4 on 2025-07-10 20:31

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueEtatMeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_etat', models.CharField(choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], max_length=20)),
                ('nouvel_etat', models.CharField(choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], max_length=20)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True, verbose_name='Motif du changement')),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Coût (FCFA)')),
                ('intervenant', models.CharField(blank=True, max_length=100, verbose_name='Intervenant/Réparateur')),
                ('duree_intervention', models.DurationField(blank=True, null=True, verbose_name="Durée de l'intervention")),
            ],
            options={
                'verbose_name': "Historique d'état",
                'verbose_name_plural': "Historiques d'états",
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='InventaireMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateTimeField(auto_now_add=True)),
                ('type_inventaire', models.CharField(choices=[('entree', "État des lieux d'entrée"), ('sortie', 'État des lieux de sortie'), ('periodique', 'Inventaire périodique'), ('maintenance', 'Inventaire maintenance'), ('assurance', 'Inventaire assurance'), ('contentieux', 'Inventaire contentieux')], default='periodique', max_length=20, verbose_name="Type d'inventaire")),
                ('nombre_meubles_total', models.PositiveIntegerField(default=0)),
                ('nombre_meubles_bon_etat', models.PositiveIntegerField(default=0)),
                ('nombre_meubles_usage', models.PositiveIntegerField(default=0)),
                ('nombre_meubles_defectueux', models.PositiveIntegerField(default=0)),
                ('nombre_meubles_hors_service', models.PositiveIntegerField(default=0)),
                ('valeur_totale_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur totale estimée (FCFA)')),
                ('observations', models.TextField(blank=True, verbose_name='Observations générales')),
                ('valide_par_gestionnaire', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('signature_locataire', models.TextField(blank=True, help_text='Signature numérique ou confirmation du locataire')),
            ],
            options={
                'verbose_name': 'Inventaire de maison',
                'verbose_name_plural': 'Inventaires de maisons',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du meuble')),
                ('numero_serie', models.CharField(help_text="Numéro d'identification unique du meuble", max_length=50, unique=True, verbose_name='Numéro de série')),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], default='bon', max_length=20, verbose_name='État du meuble')),
                ('etat_precedent', models.CharField(blank=True, choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], max_length=20, verbose_name='État précédent')),
                ('date_entree', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée")),
                ('date_derniere_verification', models.DateField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('date_dernier_entretien', models.DateField(blank=True, null=True, verbose_name='Dernier entretien')),
                ('piece', models.CharField(choices=[('salon', 'Salon'), ('chambre_1', 'Chambre 1'), ('chambre_2', 'Chambre 2'), ('chambre_3', 'Chambre 3'), ('chambre_4', 'Chambre 4'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('salle_eau', "Salle d'eau"), ('bureau', 'Bureau'), ('terrasse', 'Terrasse'), ('balcon', 'Balcon'), ('garage', 'Garage'), ('cave', 'Cave'), ('grenier', 'Grenier'), ('entree', 'Entrée'), ('couloir', 'Couloir'), ('autre', 'Autre')], default='salon', max_length=30, verbose_name='Pièce')),
                ('position_details', models.CharField(blank=True, help_text='Ex: Coin gauche, près de la fenêtre', max_length=100, verbose_name='Détails de position')),
                ('marque', models.CharField(blank=True, max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('couleur', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('materiaux', models.CharField(blank=True, max_length=100, verbose_name='Matériaux')),
                ('dimensions', models.CharField(blank=True, help_text='Ex: L120 x P60 x H75 cm', max_length=100, verbose_name='Dimensions')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids (kg)')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat (FCFA)")),
                ('valeur_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valeur actuelle estimée (FCFA)')),
                ('cout_entretien_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Coût d'entretien annuel estimé (FCFA)")),
                ('date_fin_garantie', models.DateField(blank=True, null=True, verbose_name='Fin de garantie')),
                ('numero_police_assurance', models.CharField(blank=True, max_length=50, verbose_name="Numéro de police d'assurance")),
                ('notes', models.TextField(blank=True, verbose_name='Notes et observations')),
                ('notes_internes', models.TextField(blank=True, help_text='Visibles uniquement par les gestionnaires', verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_favori', models.BooleanField(default=False, verbose_name='Marqué comme favori')),
                ('est_archive', models.BooleanField(default=False, verbose_name='Archivé')),
            ],
            options={
                'verbose_name': 'Meuble',
                'verbose_name_plural': 'Meubles',
                'ordering': ['maison', 'piece', 'type_meuble', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meubles/photos/%Y/%m/', verbose_name='Image')),
                ('titre', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('type_photo', models.CharField(choices=[('etat_general', 'État général'), ('detail', 'Détail'), ('defaut', 'Défaut/problème'), ('reparation', 'Après réparation'), ('installation', 'Installation'), ('entretien', 'Entretien')], default='etat_general', max_length=20, verbose_name='Type de photo')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
                ('taille_fichier', models.PositiveIntegerField(blank=True, null=True)),
                ('largeur', models.PositiveIntegerField(blank=True, null=True)),
                ('hauteur', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Photo de meuble',
                'verbose_name_plural': 'Photos de meubles',
                'ordering': ['-date_prise'],
            },
        ),
        migrations.CreateModel(
            name='TypeMeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('categorie', models.CharField(choices=[('chambre', 'Chambre'), ('salon', 'Salon'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('bureau', 'Bureau'), ('exterieur', 'Extérieur'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie')),
                ('icone', models.CharField(default='cube', help_text="Icône FontAwesome pour l'affichage", max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de meuble',
                'verbose_name_plural': 'Types de meubles',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
