# Generated by Django 5.2.3 on 2025-06-28 18:29

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_reservation_client_remove_reservation_maison_and_more'),
        ('meubles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventairemaison',
            name='photos',
        ),
        migrations.AddField(
            model_name='historiqueetatmeuble',
            name='duree_intervention',
            field=models.DurationField(blank=True, null=True, verbose_name="Durée de l'intervention"),
        ),
        migrations.AddField(
            model_name='historiqueetatmeuble',
            name='intervenant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Intervenant/Réparateur'),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='nombre_meubles_hors_service',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='nombre_meubles_usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='signature_locataire',
            field=models.TextField(blank=True, help_text='Signature numérique ou confirmation du locataire'),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='valeur_totale_estimee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur totale estimée (FCFA)'),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='valide_par_gestionnaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meuble',
            name='cout_entretien_annuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Coût d'entretien annuel estimé (FCFA)"),
        ),
        migrations.AddField(
            model_name='meuble',
            name='date_dernier_entretien',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier entretien'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='date_fin_garantie',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de garantie'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='est_archive',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='est_favori',
            field=models.BooleanField(default=False, verbose_name='Marqué comme favori'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='etat_precedent',
            field=models.CharField(blank=True, choices=[('bon', 'Bon état'), ('usage', "État d'usage"), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], max_length=20, verbose_name='État précédent'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='notes_internes',
            field=models.TextField(blank=True, help_text='Visibles uniquement par les gestionnaires', verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='numero_police_assurance',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro de police d'assurance"),
        ),
        migrations.AddField(
            model_name='meuble',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='position_details',
            field=models.CharField(blank=True, help_text='Ex: Coin gauche, près de la fenêtre', max_length=100, verbose_name='Détails de position'),
        ),
        migrations.AddField(
            model_name='photomeuble',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='photomeuble',
            name='hauteur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photomeuble',
            name='largeur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photomeuble',
            name='taille_fichier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typemeuble',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typemeuble',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historiqueetatmeuble',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Coût (FCFA)'),
        ),
        migrations.AlterField(
            model_name='historiqueetatmeuble',
            name='motif',
            field=models.TextField(blank=True, verbose_name='Motif du changement'),
        ),
        migrations.AlterField(
            model_name='inventairemaison',
            name='type_inventaire',
            field=models.CharField(choices=[('entree', "État des lieux d'entrée"), ('sortie', 'État des lieux de sortie'), ('periodique', 'Inventaire périodique'), ('maintenance', 'Inventaire maintenance'), ('assurance', 'Inventaire assurance'), ('contentieux', 'Inventaire contentieux')], default='periodique', max_length=20, verbose_name="Type d'inventaire"),
        ),
        migrations.AlterField(
            model_name='meuble',
            name='date_entree',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='meuble',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meuble',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes et observations'),
        ),
        migrations.AlterField(
            model_name='meuble',
            name='piece',
            field=models.CharField(choices=[('salon', 'Salon'), ('chambre_1', 'Chambre 1'), ('chambre_2', 'Chambre 2'), ('chambre_3', 'Chambre 3'), ('chambre_4', 'Chambre 4'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('salle_eau', "Salle d'eau"), ('bureau', 'Bureau'), ('terrasse', 'Terrasse'), ('balcon', 'Balcon'), ('garage', 'Garage'), ('cave', 'Cave'), ('grenier', 'Grenier'), ('entree', 'Entrée'), ('couloir', 'Couloir'), ('autre', 'Autre')], default='salon', max_length=30, verbose_name='Pièce'),
        ),
        migrations.AlterField(
            model_name='meuble',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat (FCFA)"),
        ),
        migrations.AlterField(
            model_name='meuble',
            name='valeur_actuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valeur actuelle estimée (FCFA)'),
        ),
        migrations.AlterField(
            model_name='photomeuble',
            name='image',
            field=models.ImageField(upload_to='meubles/photos/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photomeuble',
            name='type_photo',
            field=models.CharField(choices=[('etat_general', 'État général'), ('detail', 'Détail'), ('defaut', 'Défaut/problème'), ('reparation', 'Après réparation'), ('installation', 'Installation'), ('entretien', 'Entretien')], default='etat_general', max_length=20, verbose_name='Type de photo'),
        ),
        migrations.AlterField(
            model_name='typemeuble',
            name='categorie',
            field=models.CharField(choices=[('chambre', 'Chambre'), ('salon', 'Salon'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('bureau', 'Bureau'), ('exterieur', 'Extérieur'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='typemeuble',
            name='icone',
            field=models.CharField(default='cube', help_text="Icône FontAwesome pour l'affichage", max_length=50),
        ),
        migrations.AddIndex(
            model_name='historiqueetatmeuble',
            index=models.Index(fields=['meuble', '-date_changement'], name='meubles_his_meuble__b409d9_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueetatmeuble',
            index=models.Index(fields=['date_changement'], name='meubles_his_date_ch_3fdc43_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueetatmeuble',
            index=models.Index(fields=['ancien_etat', 'nouvel_etat'], name='meubles_his_ancien__5343f0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairemaison',
            index=models.Index(fields=['maison', '-date_inventaire'], name='meubles_inv_maison__1ff688_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairemaison',
            index=models.Index(fields=['type_inventaire'], name='meubles_inv_type_in_ea5808_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairemaison',
            index=models.Index(fields=['date_inventaire'], name='meubles_inv_date_in_2e1adc_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['etat', 'piece'], name='meubles_meu_etat_a6ff24_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['date_entree'], name='meubles_meu_date_en_4b85ee_idx'),
        ),
        migrations.AddIndex(
            model_name='photomeuble',
            index=models.Index(fields=['meuble', '-date_prise'], name='meubles_pho_meuble__25fc53_idx'),
        ),
        migrations.AddIndex(
            model_name='photomeuble',
            index=models.Index(fields=['type_photo'], name='meubles_pho_type_ph_6bcdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='typemeuble',
            index=models.Index(fields=['categorie'], name='meubles_typ_categor_86197a_idx'),
        ),
        migrations.AddIndex(
            model_name='typemeuble',
            index=models.Index(fields=['nom'], name='meubles_typ_nom_e79d27_idx'),
        ),
        migrations.AddConstraint(
            model_name='meuble',
            constraint=models.CheckConstraint(condition=models.Q(('prix_achat__gte', 0)), name='prix_achat_positif'),
        ),
        migrations.AddConstraint(
            model_name='meuble',
            constraint=models.CheckConstraint(condition=models.Q(('valeur_actuelle__gte', 0)), name='valeur_actuelle_positive'),
        ),
    ]
