# Generated by Django 5.2.3 on 2025-06-30 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_initial'),
        ('meubles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueetatmeuble',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='effectue_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par'),
        ),
        migrations.AddField(
            model_name='inventairemaison',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='home.maison'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meubles', to='home.maison', verbose_name='Maison'),
        ),
        migrations.AddField(
            model_name='historiqueetatmeuble',
            name='meuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_etats', to='meubles.meuble'),
        ),
        migrations.AddField(
            model_name='photomeuble',
            name='meuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meubles.meuble'),
        ),
        migrations.AddIndex(
            model_name='typemeuble',
            index=models.Index(fields=['categorie'], name='meubles_typ_categor_86197a_idx'),
        ),
        migrations.AddIndex(
            model_name='typemeuble',
            index=models.Index(fields=['nom'], name='meubles_typ_nom_e79d27_idx'),
        ),
        migrations.AddField(
            model_name='meuble',
            name='type_meuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meubles.typemeuble', verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='inventairemaison',
            index=models.Index(fields=['maison', '-date_inventaire'], name='meubles_inv_maison__1ff688_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairemaison',
            index=models.Index(fields=['type_inventaire'], name='meubles_inv_type_in_ea5808_idx'),
        ),
        migrations.AddIndex(
            model_name='inventairemaison',
            index=models.Index(fields=['date_inventaire'], name='meubles_inv_date_in_2e1adc_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueetatmeuble',
            index=models.Index(fields=['meuble', '-date_changement'], name='meubles_his_meuble__b409d9_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueetatmeuble',
            index=models.Index(fields=['date_changement'], name='meubles_his_date_ch_3fdc43_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueetatmeuble',
            index=models.Index(fields=['ancien_etat', 'nouvel_etat'], name='meubles_his_ancien__5343f0_idx'),
        ),
        migrations.AddIndex(
            model_name='photomeuble',
            index=models.Index(fields=['meuble', '-date_prise'], name='meubles_pho_meuble__25fc53_idx'),
        ),
        migrations.AddIndex(
            model_name='photomeuble',
            index=models.Index(fields=['type_photo'], name='meubles_pho_type_ph_6bcdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['maison', 'etat'], name='meubles_meu_maison__b15773_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['numero_serie'], name='meubles_meu_numero__b59e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['type_meuble'], name='meubles_meu_type_me_9163ec_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['date_derniere_verification'], name='meubles_meu_date_de_fe7755_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['etat', 'piece'], name='meubles_meu_etat_a6ff24_idx'),
        ),
        migrations.AddIndex(
            model_name='meuble',
            index=models.Index(fields=['date_entree'], name='meubles_meu_date_en_4b85ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='meuble',
            constraint=models.CheckConstraint(condition=models.Q(('prix_achat__gte', 0)), name='prix_achat_positif'),
        ),
        migrations.AddConstraint(
            model_name='meuble',
            constraint=models.CheckConstraint(condition=models.Q(('valeur_actuelle__gte', 0)), name='valeur_actuelle_positive'),
        ),
    ]
