# Generated by Django 5.2.3 on 2025-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=20, unique=True, verbose_name='Numéro')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name='Date émission')),
                ('montant_sejour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant séjour')),
                ('frais_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais supplémentaires')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('fichier_pdf', models.FileField(blank=True, upload_to='factures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
