# Generated by Django 5.2.3 on 2025-09-05 14:26

import apps.facturation.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_numero_identite'),
        ('facturation', '0002_initial'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='RepAvi Lodges', max_length=200)),
                ('adresse', models.TextField(default='Yaoundé, Cameroun')),
                ('telephone', models.CharField(default='+237 XXX XXX XXX', max_length=50)),
                ('email', models.EmailField(default='contact@repavi.com', max_length=254)),
                ('numero_contribuable', models.CharField(blank=True, max_length=50)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=Decimal('19.25'), max_digits=5)),
                ('footer_facture', models.TextField(default='Merci de votre confiance. RepAvi Lodges - Votre séjour, notre priorité.')),
            ],
            options={
                'verbose_name': 'Paramètres Facturation',
                'verbose_name_plural': 'Paramètres Facturation',
            },
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='gestionnaire',
            new_name='cree_par',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='fichier_pdf',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='frais_supplementaires',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_sejour',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='numero_facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='conditions_paiement',
            field=models.TextField(default='Paiement à réception de facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(default=apps.facturation.models.get_date_echeance_defaut),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='frais_menage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='frais_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(default=0, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='emise', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.25'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='reservations.reservation'),
        ),
    ]
