# Generated by Django 5.2.3 on 2025-09-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_parametresfacturation_alter_facture_options_and_more'),
        ('paiements', '0004_alter_echeancierpaiement_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_facture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='paiement',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='paiements.echeancierpaiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='solde_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('paiement_partiel', 'Paiement partiel'), ('paiement_final', 'Paiement final')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
