# Generated by Django 5.2.3 on 2025-09-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_facture_montant_facture_facture_paiement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_facture',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='solde_restant',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='type_facture',
        ),
        migrations.RemoveField(
            model_name='parametresfacturation',
            name='numero_contribuable',
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='delai_paiement_jours',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='frais_menage_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
