# Generated by Django 5.2.3 on 2025-09-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_remove_facture_montant_facture_and_more'),
        ('paiements', '0004_alter_echeancierpaiement_reservation'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='frais_menage',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='frais_service',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='remise',
        ),
        migrations.AddField(
            model_name='facture',
            name='echeance_paiement',
            field=models.OneToOneField(default=0, help_text='Paiement associé à cette facture', on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='paiements.echeancierpaiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_paiement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de CE paiement spécifique', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='solde_apres_paiement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde restant après ce paiement', max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='solde_avant_paiement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde restant avant ce paiement', max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('acompte', "Facture d'acompte"), ('solde', 'Facture de solde'), ('complete', 'Facture complète')], default=0, help_text='Type de facture selon le paiement', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='payee', max_length=20),
        ),
    ]
