# Generated by Django 5.2.3 on 2025-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_remove_facture_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresfacturation',
            name='conditions_generales',
            field=models.TextField(default="Paiement à réception de facture. Aucun remboursement après 24h de l'arrivée.", verbose_name='Conditions générales'),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='mentions_legales',
            field=models.TextField(default='RepAvi Lodges - Société responsabilité limitée au capital de 1.000.000 FCFA', verbose_name='Mentions légales'),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='numero_contribuable',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Contribuable'),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='numero_rccm',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° RCCM'),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='parametresfacturation',
            name='footer_facture',
            field=models.TextField(default='Merci de votre confiance. RepAvi Lodges - Votre séjour, notre priorité.', verbose_name='Pied de page facture'),
        ),
        migrations.AlterField(
            model_name='parametresfacturation',
            name='frais_menage_defaut',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]
