# Generated by Django 5.2.3 on 2025-09-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_parametresfacturation_conditions_generales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='taux_tva',
        ),
        migrations.AlterField(
            model_name='facture',
            name='conditions_paiement',
            field=models.TextField(blank=True),
        ),
    ]
