# Generated by Django 5.2.5 on 2025-08-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancierPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('acompte', 'Acompte'), ('solde', 'Solde')], max_length=20)),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant prévu')),
                ('date_echeance', models.DateField(verbose_name='Date échéance')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money_orange', 'Mobile Money Orange'), ('mobile_money_mtn', 'Mobile Money MTN'), ('cheque', 'Chèque')], max_length=30)),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Échéancier Paiement',
                'verbose_name_plural': 'Échéanciers Paiements',
                'ordering': ['date_echeance'],
            },
        ),
    ]
