<<<<<<< HEAD:avis/migrations/0002_initial.py
# Generated by Django 5.2.4 on 2025-07-10 20:31
=======
# Generated by Django 5.2.3 on 2025-08-07 12:42
>>>>>>> 9ea9fdf5ac234f463a66c620bbbe53de6e1ed62b:apps/paiements/migrations/0002_initial.py

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
    ]
