# Generated by Django 5.2.3 on 2025-08-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_initial'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='echeancierpaiement',
            unique_together={('reservation', 'type_paiement')},
        ),
    ]
