# Generated by Django 5.2.3 on 2025-08-10 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_alter_echeancierpaiement_unique_together'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeancierpaiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeanciers', to='reservations.reservation'),
        ),
    ]
