# Generated by Django 5.2.3 on 2025-07-02 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, '1 étoile - Très décevant'), (2, '2 étoiles - Décevant'), (3, '3 étoiles - Correct'), (4, '4 étoiles - Bien'), (5, '5 étoiles - Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('titre', models.CharField(help_text='Résumé en quelques mots', max_length=100, verbose_name="Titre de l'avis")),
                ('commentaire', models.TextField(help_text='Partagez votre expérience détaillée', verbose_name='Commentaire')),
                ('statut_moderation', models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('signale', 'Signalé')], default='en_attente', max_length=20, verbose_name='Statut de modération')),
                ('raison_rejet', models.TextField(blank=True, help_text='Explication en cas de rejet', verbose_name='Raison du rejet')),
                ('reponse_gestionnaire', models.TextField(blank=True, help_text='Réponse publique du gestionnaire', verbose_name='Réponse du gestionnaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Date de modération')),
                ('date_sejour', models.DateField(blank=True, help_text='Quand avez-vous séjourné dans cette maison ?', null=True, verbose_name='Date du séjour')),
                ('duree_sejour', models.PositiveIntegerField(blank=True, help_text='Combien de nuits avez-vous passées ?', null=True, verbose_name='Durée du séjour (jours)')),
                ('recommande', models.BooleanField(default=True, help_text="Recommanderiez-vous cette maison à d'autres voyageurs ?", verbose_name='Recommande cette maison')),
                ('nombre_likes', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('nombre_signalements', models.PositiveIntegerField(default=0, verbose_name='Nombre de signalements')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LikeAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Like d'avis",
                'verbose_name_plural': "Likes d'avis",
            },
        ),
        migrations.CreateModel(
            name='PhotoAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avis/photos/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, help_text='Description de la photo', max_length=200, verbose_name='Légende')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('taille_fichier', models.PositiveIntegerField(blank=True, help_text='Taille en octets', null=True)),
            ],
            options={
                'verbose_name': "Photo d'avis",
                'verbose_name_plural': "Photos d'avis",
                'ordering': ['avis', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SignalementAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('spam', 'Spam'), ('faux', 'Faux avis'), ('inapproprie', 'Contenu inapproprié'), ('hors_sujet', 'Hors sujet'), ('insultes', 'Insultes ou menaces'), ('autre', 'Autre')], max_length=20, verbose_name='Raison du signalement')),
                ('commentaire', models.TextField(blank=True, help_text='Détails sur le signalement', verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': "Signalement d'avis",
                'verbose_name_plural': "Signalements d'avis",
            },
        ),
    ]
