# Generated by Django 5.2.3 on 2025-07-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avis', '0001_initial'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='avis',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='home.maison', verbose_name='Maison'),
        ),
        migrations.AddField(
            model_name='avis',
            name='modere_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['GESTIONNAIRE', 'SUPER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_moderes', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par'),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['GESTIONNAIRE', 'SUPER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_avis', to=settings.AUTH_USER_MODEL, verbose_name='Réponse par'),
        ),
        migrations.AddField(
            model_name='likeavis',
            name='avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='avis.avis'),
        ),
        migrations.AddField(
            model_name='likeavis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoavis',
            name='avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='avis.avis', verbose_name='Avis'),
        ),
        migrations.AddField(
            model_name='signalementavis',
            name='avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='avis.avis'),
        ),
        migrations.AddField(
            model_name='signalementavis',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AddField(
            model_name='signalementavis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Signalé par'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['maison', 'statut_moderation'], name='avis_avis_maison__436adb_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['client'], name='avis_avis_client__97828f_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['note'], name='avis_avis_note_b68d14_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['date_creation'], name='avis_avis_date_cr_03ddde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('client', 'maison')},
        ),
        migrations.AlterUniqueTogether(
            name='likeavis',
            unique_together={('avis', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='signalementavis',
            unique_together={('avis', 'user')},
        ),
    ]
