# Generated by Django 5.2.3 on 2025-07-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='avis',
            name='statut_moderation',
        ),
    ]
