# Generated by Django 5.2.3 on 2025-07-02 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Partagez votre expérience détaillée (optionnel)', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='modere_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_moderes', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='reponse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_avis', to=settings.AUTH_USER_MODEL, verbose_name='Réponse par'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='titre',
            field=models.CharField(blank=True, help_text='Résumé en quelques mots (optionnel)', max_length=100, verbose_name="Titre de l'avis"),
        ),
    ]
