# Generated by Django 5.2.4 on 2025-07-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('date_entree_reelle', models.DateField(blank=True, null=True, verbose_name="Date d'entrée réelle")),
                ('date_sortie_reelle', models.DateField(blank=True, null=True, verbose_name='Date de sortie réelle')),
                ('montant_paye', models.PositiveIntegerField(default=0, verbose_name='Montant payé (FCFA)')),
                ('montant_restant', models.PositiveIntegerField(default=0, verbose_name='Montant restant (FCFA)')),
                ('montant_total', models.PositiveIntegerField(verbose_name='Montant total (FCFA)')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('type_attribution', models.CharField(choices=[('directe', 'Attribution directe'), ('reservation', 'Via réservation')], default='directe', max_length=20, verbose_name="Type d'attribution")),
                ('notes_admin', models.TextField(blank=True, verbose_name='Notes administratives')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('prix_special', models.PositiveIntegerField(blank=True, help_text='Prix spécial pour cette date (optionnel)', null=True, verbose_name='Prix spécial (FCFA)')),
                ('raison_indisponibilite', models.CharField(blank=True, max_length=255, verbose_name="Raison de l'indisponibilité")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['maison', 'date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_globale', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note globale')),
                ('note_proprete', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Propreté')),
                ('note_equipements', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Équipements')),
                ('note_emplacement', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Emplacement')),
                ('note_rapport_qualite_prix', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Rapport qualité/prix')),
                ('commentaire', models.TextField(help_text='Partagez votre expérience', verbose_name='Commentaire')),
                ('points_positifs', models.TextField(blank=True, verbose_name='Points positifs')),
                ('points_amelioration', models.TextField(blank=True, verbose_name='Points à améliorer')),
                ('recommande', models.BooleanField(verbose_name='Recommanderiez-vous cette maison ?')),
                ('reviendrait', models.BooleanField(verbose_name='Reviendriez-vous ?')),
                ('approuve', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('raison_rejet', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('reponse_gestionnaire', models.TextField(blank=True, verbose_name='Réponse du gestionnaire')),
                ('date_reponse_gestionnaire', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Évaluation de réservation',
                'verbose_name_plural': 'Évaluations de réservations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaction', models.CharField(max_length=100, unique=True, verbose_name='Numéro de transaction')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('frais', models.PositiveIntegerField(default=0, verbose_name='Frais (FCFA)')),
                ('montant_net', models.PositiveIntegerField(default=0, verbose_name='Montant net (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reference_externe', models.CharField(blank=True, help_text='Référence du système de paiement externe', max_length=255, verbose_name='Référence externe')),
                ('reponse_gateway', models.JSONField(blank=True, default=dict, help_text='Réponse complète du système de paiement', verbose_name='Réponse du gateway')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_echec', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Numéro de réservation')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('heure_arrivee', models.TimeField(blank=True, help_text="Heure d'arrivée prévue", null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, help_text='Heure de départ prévue', null=True, verbose_name='Heure de départ')),
                ('nombre_personnes', models.PositiveIntegerField(verbose_name='Nombre de personnes')),
                ('nombre_nuits', models.PositiveIntegerField(editable=False, verbose_name='Nombre de nuits')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('prix_par_nuit', models.PositiveIntegerField(verbose_name='Prix par nuit (FCFA)')),
                ('frais_service', models.PositiveIntegerField(default=0, verbose_name='Frais de service (FCFA)')),
                ('reduction_montant', models.PositiveIntegerField(default=0, verbose_name='Montant de la réduction (FCFA)')),
                ('reduction_raison', models.CharField(blank=True, max_length=255, verbose_name='Raison de la réduction')),
                ('sous_total', models.PositiveIntegerField(default=0, verbose_name='Sous-total (FCFA)')),
                ('prix_total', models.PositiveIntegerField(verbose_name='Prix total (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('integral', 'Paiement intégral'), ('acompte', 'Acompte (30%)'), ('echelonne', 'Paiement échelonné')], default='integral', max_length=20, verbose_name='Mode de paiement')),
                ('montant_acompte', models.PositiveIntegerField(blank=True, null=True, verbose_name="Montant de l'acompte (FCFA)")),
                ('commentaire_client', models.TextField(blank=True, help_text='Demandes spéciales, remarques...', verbose_name='Commentaire du client')),
                ('commentaire_gestionnaire', models.TextField(blank=True, help_text='Notes internes, instructions...', verbose_name='Notes du gestionnaire')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence - Nom")),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence - Téléphone")),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('raison_annulation', models.TextField(blank=True, verbose_name="Raison de l'annulation")),
                ('rappel_envoye', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('evaluation_demandee', models.BooleanField(default=False, verbose_name='Évaluation demandée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ip_creation', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TypePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('frais_pourcentage', models.DecimalField(decimal_places=2, default=0, help_text='Frais en pourcentage (ex: 2.5 pour 2.5%)', max_digits=5, verbose_name='Frais (%)')),
                ('frais_fixe', models.PositiveIntegerField(default=0, help_text='Frais fixe en FCFA', verbose_name='Frais fixe (FCFA)')),
                ('icone', models.CharField(default='credit-card', max_length=50, verbose_name='Icône')),
                ('couleur', models.CharField(default='blue', max_length=20, verbose_name='Couleur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de paiement',
                'verbose_name_plural': 'Types de paiement',
                'ordering': ['nom'],
            },
        ),
    ]
