# Generated by Django 5.2.3 on 2025-07-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.maison', verbose_name='Maison'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AddField(
            model_name='evaluationreservation',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.typepaiement', verbose_name='Type de paiement'),
        ),
        migrations.AddIndex(
            model_name='disponibilite',
            index=models.Index(fields=['maison', 'date'], name='reservation_maison__bf8644_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilite',
            index=models.Index(fields=['date', 'disponible'], name='reservation_date_2eb2c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilite',
            unique_together={('maison', 'date')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['numero'], name='reservation_numero_1bb553_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['client'], name='reservation_client__32bdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['maison'], name='reservation_maison__23d086_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['statut'], name='reservation_statut_edd3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date_debut', 'date_fin'], name='reservation_date_de_8de59c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date_creation'], name='reservation_date_cr_5268a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='date_fin_after_date_debut'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_personnes__gte', 1)), name='nombre_personnes_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('prix_par_nuit__gte', 0)), name='prix_par_nuit_positive'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['numero_transaction'], name='reservation_numero__b38a59_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reservation'], name='reservation_reserva_0e7e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='reservation_statut_3d7575_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_creation'], name='reservation_date_cr_322d5b_idx'),
        ),
    ]
