# Generated by Django 5.2.3 on 2025-07-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='frais_service',
            field=models.PositiveIntegerField(default=0, verbose_name='Frais de service (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_par_nuit',
            field=models.PositiveIntegerField(verbose_name='Prix par nuit (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.PositiveIntegerField(verbose_name='Prix total (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reduction_montant',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant de la réduction (FCFA)'),
        ),
    ]
