# Generated by Django 5.2.3 on 2025-07-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_frais_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilite',
            name='prix_special',
            field=models.PositiveIntegerField(blank=True, help_text='Prix spécial pour cette date (optionnel)', null=True, verbose_name='Prix spécial (FCFA)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='frais',
            field=models.PositiveIntegerField(default=0, verbose_name='Frais (FCFA)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.PositiveIntegerField(verbose_name='Montant (FCFA)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_net',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant net (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant_acompte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Montant de l'acompte (FCFA)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='sous_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Sous-total (FCFA)'),
        ),
        migrations.AlterField(
            model_name='typepaiement',
            name='frais_fixe',
            field=models.PositiveIntegerField(default=0, help_text='Frais fixe en FCFA', verbose_name='Frais fixe (FCFA)'),
        ),
    ]
