# Generated by Django 5.2.3 on 2025-07-10 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_maison_prix_par_nuit'),
        ('reservations', '0004_alter_disponibilite_prix_special_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('date_entree_reelle', models.DateField(blank=True, null=True, verbose_name="Date d'entrée réelle")),
                ('date_sortie_reelle', models.DateField(blank=True, null=True, verbose_name='Date de sortie réelle')),
                ('montant_paye', models.PositiveIntegerField(default=0, verbose_name='Montant payé (FCFA)')),
                ('montant_restant', models.PositiveIntegerField(default=0, verbose_name='Montant restant (FCFA)')),
                ('montant_total', models.PositiveIntegerField(verbose_name='Montant total (FCFA)')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('type_attribution', models.CharField(choices=[('directe', 'Attribution directe'), ('reservation', 'Via réservation')], default='directe', max_length=20, verbose_name="Type d'attribution")),
                ('notes_admin', models.TextField(blank=True, verbose_name='Notes administratives')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='home.maison', verbose_name='Maison')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution', to='reservations.reservation', verbose_name='Réservation liée')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['client'], name='reservation_client__c7c046_idx'), models.Index(fields=['maison'], name='reservation_maison__ab77d5_idx'), models.Index(fields=['statut'], name='reservation_statut_d885c5_idx'), models.Index(fields=['date_entree', 'date_sortie'], name='reservation_date_en_ffd070_idx')],
            },
        ),
    ]
