# Generated by Django 5.2.3 on 2025-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_derniere_activite_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('gestionnaire', 'Gestionnaire'), ('receptionniste', 'Réceptionniste')], default='gestionnaire', max_length=20),
        ),
    ]
