# Generated by Django 5.2.3 on 2025-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='details',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
