# Generated by Django 5.2.2 on 2025-06-09 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='blue', max_length=20)),
            ],
            options={
                'verbose_name': 'Catégorie de maison',
                'verbose_name_plural': 'Catégories de maisons',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('departement', models.CharField(max_length=100)),
                ('pays', models.CharField(default='France', max_length=100)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=255)),
                ('capacite_personnes', models.PositiveIntegerField()),
                ('nombre_chambres', models.PositiveIntegerField()),
                ('nombre_salles_bain', models.PositiveIntegerField()),
                ('superficie', models.PositiveIntegerField(help_text='Superficie en m²')),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text="Afficher sur la page d'accueil")),
                ('wifi', models.BooleanField(default=True)),
                ('parking', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('lave_vaisselle', models.BooleanField(default=False)),
                ('machine_laver', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categoriemaison')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ville')),
            ],
            options={
                'verbose_name': 'Maison',
                'verbose_name_plural': 'Maisons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maisons/photos/')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.maison')),
            ],
            options={
                'verbose_name': 'Photo de maison',
                'verbose_name_plural': 'Photos de maisons',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.maison')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
