# Generated by Django 5.2.3 on 2025-07-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='gestionnaire',
            field=models.ForeignKey(help_text='Gestionnaire responsable de cette maison', limit_choices_to={'role__in': ['GESTIONNAIRE', 'SUPER_ADMIN']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire'),
        ),
        migrations.AddField(
            model_name='maison',
            name='locataire_actuel',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maisons_occupees', to=settings.AUTH_USER_MODEL, verbose_name='Locataire actuel'),
        ),
        migrations.AddField(
            model_name='photomaison',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.maison'),
        ),
        migrations.AddField(
            model_name='maison',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ville', verbose_name='Ville'),
        ),
        migrations.AddIndex(
            model_name='photomaison',
            index=models.Index(fields=['maison', 'principale'], name='home_photom_maison__bdc03d_idx'),
        ),
        migrations.AddIndex(
            model_name='photomaison',
            index=models.Index(fields=['maison', 'ordre'], name='home_photom_maison__a0210f_idx'),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['statut_occupation'], name='home_maison_statut__0822a2_idx'),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['disponible'], name='home_maison_disponi_68efba_idx'),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['gestionnaire'], name='home_maison_gestion_6e7f95_idx'),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['ville'], name='home_maison_ville_i_c45335_idx'),
        ),
    ]
