# Generated by Django 5.2.3 on 2025-06-28 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reservation_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='maison',
        ),
        migrations.AlterModelOptions(
            name='categoriemaison',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie de maison', 'verbose_name_plural': 'Catégories de maisons'},
        ),
        migrations.AlterModelOptions(
            name='photomaison',
            options={'ordering': ['maison', 'ordre', 'id'], 'verbose_name': 'Photo de maison', 'verbose_name_plural': 'Photos de maisons'},
        ),
        migrations.AlterModelOptions(
            name='ville',
            options={'ordering': ['nom'], 'verbose_name': 'Ville', 'verbose_name_plural': 'Villes'},
        ),
        migrations.AddField(
            model_name='categoriemaison',
            name='icone',
            field=models.CharField(default='home', help_text="Icône pour l'affichage", max_length=50),
        ),
        migrations.AddField(
            model_name='maison',
            name='balcon',
            field=models.BooleanField(default=False, verbose_name='Balcon'),
        ),
        migrations.AddField(
            model_name='maison',
            name='date_fin_location',
            field=models.DateField(blank=True, help_text='Date prévue de libération de la maison', null=True, verbose_name='Date de fin de location'),
        ),
        migrations.AddField(
            model_name='maison',
            name='locataire_actuel',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maisons_occupees', to=settings.AUTH_USER_MODEL, verbose_name='Locataire actuel'),
        ),
        migrations.AddField(
            model_name='maison',
            name='numero',
            field=models.CharField(default=1, help_text="Numéro d'identification unique", max_length=10, unique=True, verbose_name='Numéro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maison',
            name='statut_occupation',
            field=models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('maintenance', 'En maintenance'), ('indisponible', 'Indisponible')], default='libre', max_length=20, verbose_name="Statut d'occupation"),
        ),
        migrations.AddField(
            model_name='maison',
            name='terrasse',
            field=models.BooleanField(default=False, verbose_name='Terrasse'),
        ),
        migrations.AddField(
            model_name='photomaison',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photomaison',
            name='taille_fichier',
            field=models.PositiveIntegerField(blank=True, help_text='Taille en octets', null=True),
        ),
        migrations.AddField(
            model_name='photomaison',
            name='type_photo',
            field=models.CharField(choices=[('exterieur', 'Extérieur'), ('salon', 'Salon'), ('chambre', 'Chambre'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de photo'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='capacite_personnes',
            field=models.PositiveIntegerField(verbose_name='Capacité (personnes)'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categoriemaison', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='climatisation',
            field=models.BooleanField(default=False, verbose_name='Climatisation'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible à la location'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='featured',
            field=models.BooleanField(default=False, help_text="Afficher sur la page d'accueil", verbose_name='Mise en avant'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='jardin',
            field=models.BooleanField(default=False, verbose_name='Jardin'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='lave_vaisselle',
            field=models.BooleanField(default=False, verbose_name='Lave-vaisselle'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='machine_laver',
            field=models.BooleanField(default=False, verbose_name='Machine à laver'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom de la maison'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='nombre_chambres',
            field=models.PositiveIntegerField(verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='nombre_salles_bain',
            field=models.PositiveIntegerField(verbose_name='Nombre de salles de bain'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='piscine',
            field=models.BooleanField(default=False, verbose_name='Piscine'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='prix_par_nuit',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par nuit (FCFA)'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='superficie',
            field=models.PositiveIntegerField(help_text='Superficie en m²', verbose_name='Superficie (m²)'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ville', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='wifi',
            field=models.BooleanField(default=True, verbose_name='WiFi'),
        ),
        migrations.AlterField(
            model_name='photomaison',
            name='image',
            field=models.ImageField(upload_to='maisons/photos/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photomaison',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='photomaison',
            name='principale',
            field=models.BooleanField(default=False, verbose_name='Photo principale'),
        ),
        migrations.AlterField(
            model_name='photomaison',
            name='titre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='pays',
            field=models.CharField(default='Cameroun', max_length=100),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['statut_occupation'], name='home_maison_statut__0822a2_idx'),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['disponible'], name='home_maison_disponi_68efba_idx'),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['gestionnaire'], name='home_maison_gestion_6e7f95_idx'),
        ),
        migrations.AddIndex(
            model_name='maison',
            index=models.Index(fields=['ville'], name='home_maison_ville_i_c45335_idx'),
        ),
        migrations.AddIndex(
            model_name='photomaison',
            index=models.Index(fields=['maison', 'principale'], name='home_photom_maison__bdc03d_idx'),
        ),
        migrations.AddIndex(
            model_name='photomaison',
            index=models.Index(fields=['maison', 'ordre'], name='home_photom_maison__a0210f_idx'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
