# Generated by Django 5.2.3 on 2025-07-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='prix_par_nuit',
            field=models.PositiveIntegerField(verbose_name='Prix par nuit (FCFA)'),
        ),
    ]
