# Generated by Django 5.2.5 on 2025-08-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Numéro')),
                ('type_logement', models.CharField(choices=[('studio', 'Studio'), ('t1', 'T1'), ('t2', 'T2')], max_length=10, verbose_name='Type')),
                ('maison', models.CharField(max_length=100, verbose_name='Maison')),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit (FCFA)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('maintenance', 'Maintenance')], default='disponible', max_length=20, verbose_name='Statut')),
                ('equipements', models.JSONField(default=list, help_text='Liste simple : TV, Frigo, Climatisation, etc.', verbose_name='Équipements')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAppartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piece', models.CharField(max_length=50, verbose_name='Pièce')),
                ('photo', models.ImageField(upload_to='appartements/photos/')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='appartements.appartement')),
            ],
            options={
                'verbose_name': 'Photo Appartement',
                'verbose_name_plural': 'Photos Appartements',
                'ordering': ['ordre', 'nom_piece'],
            },
        ),
    ]
