# Generated by Django 5.2.3 on 2025-08-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementAppartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom équipement')),
                ('etat', models.CharField(choices=[('bon', 'Bon'), ('usage', 'Usage'), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], default='bon', max_length=20)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat (FCFA)")),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('photo', models.ImageField(blank=True, upload_to='inventaire/')),
                ('commentaire', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartements.appartement')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['appartement__numero', 'nom'],
            },
        ),
    ]
