# Generated by Django 5.2.3 on 2025-08-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0001_initial'),
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementappartement',
            name='appartement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaire_equipements', to='appartements.appartement', verbose_name='Appartement'),
        ),
        migrations.AlterField(
            model_name='equipementappartement',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Notes et commentaires'),
        ),
        migrations.AlterField(
            model_name='equipementappartement',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon'), ('usage', 'Usage'), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service')], default='bon', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='equipementappartement',
            name='photo',
            field=models.ImageField(blank=True, upload_to='inventaire/', verbose_name='Photo'),
        ),
        migrations.AddIndex(
            model_name='equipementappartement',
            index=models.Index(fields=['appartement', 'etat'], name='inventaire__apparte_2b3ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='equipementappartement',
            index=models.Index(fields=['etat'], name='inventaire__etat_476eee_idx'),
        ),
        migrations.AddIndex(
            model_name='equipementappartement',
            index=models.Index(fields=['date_creation'], name='inventaire__date_cr_3a9bcf_idx'),
        ),
    ]
