# Generated by Django 5.2.5 on 2025-08-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('piece_identite', models.ImageField(upload_to='clients/documents/', verbose_name="Pièce d'identité (photo)")),
                ('adresse_residence', models.TextField(verbose_name='Résidence habituelle')),
                ('contact_urgence_nom', models.CharField(max_length=100, verbose_name='Contact urgence - Nom')),
                ('contact_urgence_tel', models.CharField(max_length=20, verbose_name='Contact urgence - Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
