# Generated by Django 5.2.3 on 2025-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='numero_identite',
            field=models.CharField(default=1, max_length=100, verbose_name='Numéro de CNI ou Passeport'),
            preserve_default=False,
        ),
    ]
