# Generated by Django 5.2.3 on 2025-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_numero_identite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_identite',
            field=models.CharField(help_text="Numéro de CNI, passeport ou autre pièce d'identité", max_length=50, verbose_name="Numéro d'identité"),
        ),
    ]
