# Generated by Django 5.2.3 on 2025-12-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_numero_identite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Cette adresse email est déjà utilisée par un autre client.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_identite',
            field=models.CharField(error_messages={'unique': "Ce numéro d'identité est déjà utilisé par un autre client."}, help_text="Numéro de CNI, passeport ou autre pièce d'identité", max_length=50, unique=True, verbose_name="Numéro d'identité"),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(error_messages={'unique': 'Ce numéro de téléphone est déjà utilisé par un autre client.'}, max_length=20, unique=True, verbose_name='Téléphone'),
        ),
    ]
