# Generated by Django 5.2.3 on 2025-12-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_email_alter_client_numero_identite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone_code_pays',
            field=models.CharField(default='+237', help_text='Code pays (ex: +237 pour le Cameroun)', max_length=10, verbose_name='Code pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(help_text='Numéro sans le code pays', max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('telephone_code_pays', 'telephone'), name='unique_telephone_complet', violation_error_message='Ce numéro de téléphone est déjà utilisé par un autre client.'),
        ),
    ]
