# Generated by Django 5.2.3 on 2025-12-15 11:19

from django.db import migrations
import re


def separer_code_pays_et_numero(apps, schema_editor):
    """Sépare les numéros de téléphone existants en code pays et numéro"""
    Client = apps.get_model('clients', 'Client')

    # Suivre les combinaisons code_pays + numéro déjà vues
    telephones_vus = {}

    for client in Client.objects.all():
        telephone_complet = client.telephone.strip()

        # Patterns de codes pays courants
        codes_pays = [
            '+237', '+33', '+1', '+44', '+32', '+41',
            '+225', '+221', '+243', '+242', '+241', '+236'
        ]

        # Chercher si le numéro commence par un code pays
        code_pays_trouve = None
        for code in codes_pays:
            if telephone_complet.startswith(code):
                code_pays_trouve = code
                break

        if code_pays_trouve:
            # Séparer le code pays du numéro
            client.telephone_code_pays = code_pays_trouve
            # Enlever le code pays et les espaces/caractères spéciaux au début
            numero = telephone_complet[len(code_pays_trouve):].strip()
        else:
            # Pas de code pays trouvé, on suppose que c'est +237 (Cameroun)
            client.telephone_code_pays = '+237'
            numero = telephone_complet

        # Vérifier si cette combinaison existe déjà
        cle = (client.telephone_code_pays, numero)
        if cle in telephones_vus:
            # Ajouter un suffixe pour rendre unique
            numero = f"{numero}_dup_{client.id}"
        else:
            telephones_vus[cle] = client.id

        client.telephone = numero
        client.save()


def reverse_separer(apps, schema_editor):
    """Reconstituer les numéros de téléphone complets"""
    Client = apps.get_model('clients', 'Client')

    for client in Client.objects.all():
        # Reconstituer le numéro complet
        client.telephone = f"{client.telephone_code_pays} {client.telephone}".strip()
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_telephone_code_pays_alter_client_telephone_and_more'),
    ]

    operations = [
        migrations.RunPython(separer_code_pays_et_numero, reverse_separer),
    ]
