# Generated by Django 5.2.3 on 2025-12-15 11:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_separer_telephones'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_telephone_complet',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone_code_pays',
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Ce numéro de téléphone est déjà utilisé par un autre client.'}, help_text='Format international (ex: +237 6XX XXX XXX)', max_length=128, region='CM', unique=True, verbose_name='Téléphone'),
        ),
    ]
