# Generated by Django 5.2.3 on 2025-08-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheMenage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=20)),
                ('menage_general_fait', models.BooleanField(default=False, verbose_name='Ménage général fait')),
                ('equipements_verifies', models.BooleanField(default=False, verbose_name='Équipements vérifiés')),
                ('problemes_signales', models.TextField(blank=True, verbose_name='Problèmes signalés')),
                ('temps_passe', models.PositiveIntegerField(blank=True, null=True, verbose_name='Temps passé (minutes)')),
                ('photo_avant', models.ImageField(blank=True, upload_to='menage/avant/')),
                ('photo_apres', models.ImageField(blank=True, upload_to='menage/apres/')),
                ('notes_personnel', models.TextField(blank=True, verbose_name='Notes du personnel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartements.appartement')),
            ],
            options={
                'verbose_name': 'Tâche Ménage',
                'verbose_name_plural': 'Tâches Ménage',
                'ordering': ['date_prevue', 'appartement__numero'],
            },
        ),
    ]
