# Generated by Django 5.2.3 on 2025-09-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='tachemenage',
            name='taches_a_effectuer',
            field=models.ManyToManyField(blank=True, to='menage.typetache'),
        ),
    ]
