# Generated by Django 5.2.3 on 2025-10-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0001_initial'),
        ('menage', '0003_typetache_tachemenage_taches_a_effectuer'),
        ('reservations', '0003_reservation_reduction_alter_reservation_statut'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tachemenage',
            unique_together={('appartement', 'date_prevue')},
        ),
        migrations.AddField(
            model_name='tachemenage',
            name='rapport',
            field=models.TextField(blank=True, help_text='État de la maison, meubles, problèmes constatés, etc.', verbose_name='Rapport de ménage'),
        ),
        migrations.AlterField(
            model_name='tachemenage',
            name='appartement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_menage', to='appartements.appartement'),
        ),
        migrations.AlterField(
            model_name='tachemenage',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Réservation qui a déclenché cette tâche (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation'),
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='equipements_verifies',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='menage_general_fait',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='notes_personnel',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='photo_apres',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='photo_avant',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='problemes_signales',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='taches_a_effectuer',
        ),
        migrations.RemoveField(
            model_name='tachemenage',
            name='temps_passe',
        ),
        migrations.DeleteModel(
            name='TypeTache',
        ),
    ]
